config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: "tag"

  get 'profile/index'

  resources :posts do
  	resources :comments
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  resources :comments do
  	resources :comments
    put "like", to: "comments#upvote"
    put "dislike", to: "comments#downvote"
  end

  devise_for :users, controllers: { sessions: 'user/sessions' }

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
	belongs_to :user, optional: true
	has_many :comments, as: :commentable

	acts_as_votable

	def post
		commentable.is_a?(Post) ? commentable : commentable.post
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_commentable
  respond_to :json
  #before_action :upvote

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    #@comment = @commentable.comments.find(params[:id])
    @comment = Comment.find(params[:id])
    if current_user == @comment.user
      if @comment.update(comment_params)
        redirect_to @comment, notice: "Your comment was successfully updated"
      else
        render 'index'
      end
    else
      redirect_back fallback_location: root_path, notice: 'You are not authorized to edit'
    end
  end

  def show
    redirect_back fallback_location: root_path
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if user_signed_in?
      @comment.user_id = current_user.id
    end
    if @comment.save
      redirect_back fallback_location: root_path, notice: 'Your comment was successfully posted!'
    else
      redirect_back fallback_location: root_path, notice: "Your comment wasn't posted!"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user == @comment.user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_back fallback_location: root_path, notice: 'You are not authorized to delete'
    end
  end

  def upvote
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable.downvote_by current_user
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
  end

end

app/helpers/comments__helper.rb
module CommentsHelper
  def cache_key_for_comment(comment)
    "comment/#{comment.updated_at}"
  end
end

app/views/comments/_comment.html.erb
<div class="post-skeleton" id="comment-content">

  <div class="votes">
    <%= link_to comment_like_path(comment), method: :put do %>
      <%=image_tag("up.png") %>
    <% end %>
    <%= comment.get_upvotes.size - comment.get_downvotes.size%>
    <%= link_to comment_dislike_path(comment), method: :put do %>
      <%=image_tag("down.png") %>
    <% end %>
  </div>

  <div class="post-card" id="comment-bicontent">
    <li>
      <small>by
        <% if comment.user.nil? %>
          anonymous
        <% else %>
          <%= comment.user.email %>,
        <% end %>
         <%= time_ago_in_words(comment.created_at) %> ago</small><br>

      <%= comment.body %> <br>

      <%= form_for [comment, Comment.new] do |f| %>
          <%= f.text_area :body, placeholder: "Add a Reply", :id=>"reply-content" %><br/>
          <%= f.submit "Reply"  %>
      <% end %>

      <% if user_signed_in? and current_user == comment.user%>
        <div id="delete/edit">
          <div id="delete"><%= link_to "Delete",comment_path(comment),
                                       :data => {:confirm => "Are you sure that you want to delete the comment?",
                                                 :method => "delete"} %></div>
          <div id="edit"><%= link_to "Edit", edit_comment_url(comment) %></div>
        </div><br>
      <% end %>

      <ul style="list-style-type:none">
          <%= render partial: 'comments/comment', collection: comment.comments %>
      </ul>

    </li>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment, cached: true%>

<%= link_to 'Show Post', @comment.post %> |
<%= link_to 'Back to Frontpage', posts_path %>