config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: "tag"

  get 'profile/index'

  resources :posts do
  	resources :comments
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  resources :comments do
  	resources :comments
    put "like", to: "comments#upvote"
    put "dislike", to: "comments#downvote"
  end

  devise_for :users, controllers: { sessions: 'user/sessions' }

end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :title
	validates :img, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }

	belongs_to :user, optional: true
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings

	has_many :comments, as: :commentable

	acts_as_votable

	def all_tags=(names)
		# names can look like this "cute, animal, dog"
		self.tags = names.split(',').map do |name|
			name = name.lstrip.rstrip
			Tag.where(name: name).first_or_create!
		end
	end

	def all_tags
		tags.map(&:name).join(", ")
	end


	def self.tagged_with(name)
		Tag.find_by_name(name)&.posts
		# if Tag.find_by_name(name) != nil
		# 	Tag.find_by_name(name).posts
		# else
  			
  # 		end

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_post, only: [:show]
  before_action :check_access, only: [:edit, :update, :destroy]
  respond_to :json

  # GET /posts
  # GET /posts.json
  def index
    # @posts = if params[:search]
    #   Post.where('title LIKE ?', "%#{params[:search]}%").order('id DESC')
    # else
    #   Post.all.order('id DESC')
    # end

    if params[:tag].present? and not params[:tag].nil?
      @posts_tagged = Post.tagged_with(params[:tag])
      if @posts_tagged.blank?
        #@posts = Post.all
        redirect_to root_path, notice: 'Invalid Search Tag'
      else
        @posts = @posts_tagged.paginate(page: params[:page], per_page: 5).order('created_at DESC')
      end
    else
      @posts = Post.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    if user_signed_in?
      @post = current_user.posts.new(post_params)
    else
      @post = Post.new(post_params)
    end

    respond_to do |format|
      if @post.save
        flash.now[:notice] = "Post was successfully created"
        format.html { render 'posts/show'}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash.now[:notice] = "Post was successfully updated"
        format.html { render 'posts/show' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash.now[:notice] = "Post was successfully destroyed"
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_back fallback_location: root_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :img, :all_tags, :tag)
    end


    def check_access
      @post = Post.find(params[:id])
      if current_user != @post.user
        respond_to do |format|
          format.html { redirect_to @post, notice: 'You are not authorized to make changes to this post' }
          format.json { render json: @post.errors, status: :unprocessable_entity}
        end
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_links(tags)
		tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
	
	def user_ownes_post?(post)
		return current_user == post.user 
	end

  def cache_key_for_post(post)
    "post/#{post.id}/#{post.updated_at}"
  end

  def cache_key_for_posts_table
    # this needs to be checked posts_table or show_posts_table
    ("posts_table/#{Post.maximum(:updated_at)}/"
    + Comment.maximum(:updated_at).to_s)
  end
end

app/views/posts/_form.html.erb
<div class="addpost-wrap">
  <div id="cross"><%=link_to image_tag("cancel.png"), post_path %></div>

  <h2>Edit Post</h2>
<%= form_with(model: post, local: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="addpost-form">
    <p>
      <%= f.text_field :title, :id=> "title", :placeholder=> "Title"%>
    </p>

    <p>
      <%= f.text_field :img, :id=> "image", :placeholder=> "Image URL" %>
    </p>

    <p>
      <%= f.text_field :all_tags, :id=> "tags", :placeholder=> "All tags" %>
    </p>

    <p>
      <%= f.submit :id=> "submit" %>
    </p>
  </div>
<% end %>

</div>

app/views/posts/_post.html.erb
<br>
  <div class="post-skeleton">
    <div class=<%= user_signed_in? ? "votes" : "votes-not-signed-in" %>>

        <%= link_to like_post_path(post), method: :put do %>
          <%=image_tag("up.png") %>
          <p id="vote-number"><%= post.get_upvotes.size - post.get_downvotes.size%></p>
          <%if !user_signed_in? %>
          <span class="tooltiptext">Sign up/login to vote!!</span>
          <%end %>
        <% end %>
        <%= link_to dislike_post_path(post), method: :put do %>
          <%=image_tag("down.png") %>
        <% end %>
    </div>


  <div class="post-card">
    <div id="posted-by"><small>Posted by </small>
      <% if post.user%>
        <small><%= post.user.email %></small>
      <% else %>
        <small>anonymous</small>
      <% end %>
      <small><%= time_ago_in_words(post.created_at) %> ago</small>
    </div>
    <div id="post-title"><%= link_to post do %><%= post.title %><% end %></div>
    <div><%= link_to post do %><img src="<%= post.img %>" width="100%" height="100%"/><% end %></div>
  </div>
  </div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<br><br><br>
<div class="welcome">
  <!-- <%= link_to 'New Post', new_post_path%> 
  -->
</div>

<!--
params[:search] - used for keeping the search term in the field after a search
name: nil - used for eliminate the "commit=Search" in the URL after a search
 -->
<!-- <h3>Search for memes</h3>
<%= form_tag(posts_path, method: :get) do %>

	<%= text_field_tag :tag, params[:tag], autofocus: true, :required => 'required' %>
	<%= submit_tag 'Search', name: nil %>
<% end %> -->
</br>

<div class="content-posts">
  <%= render 'show_posts_table' %>
</div>

app/views/posts/new.html.erb
<div class="addpost-wrap">
  <div id="cross"><%=link_to image_tag("cancel.png"), root_path %></div>

  <h2>Add Post</h2>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="addpost-form">
      <p>
        <%= f.text_field :title, :id=> "title", :placeholder=> "Title"%>
      </p>

      <p>
        <%= f.text_field :img, :id=> "image", :placeholder=> "Image URL" %>
      </p>

      <p>
        <%= f.text_field :all_tags, :id=> "tags", :placeholder=> "All tags" %>
      </p>

      <p>
          <%= f.submit :id=> "submit" %>
      </p>
<% end %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="content-posts">
  <br><br><br><br><br>
  <div class="post-skeleton">

    <div class=<%= user_signed_in? ? "votes" : "votes-not-signed-in" %>>

      <%= link_to like_post_path(@post), method: :put do %>
        <%=image_tag("up.png") %>
        <p id="vote-number"><%= @post.get_upvotes.size - @post.get_downvotes.size%></p>
        <%if !user_signed_in? %>
          <span class="tooltiptext">Sign up/login to vote!!</span>
        <%end %>
      <% end %>
      <%= link_to dislike_post_path(@post), method: :put do %>
        <%=image_tag("down.png") %>
      <% end %>
    </div>

    <div class="post-card">
      <div id="cancel"><%=link_to image_tag("cancel.png"), root_path %></div>
      <div id="posted-by"><small>Posted by </small>
        <% if @post.user%>
          <small><%= @post.user.email %></small>
        <% else %>
          <small>anonymous</small>
        <% end %>
        <small><%= time_ago_in_words(@post.created_at) %> ago</small>
      </div>
      <div id="post-title"><%= link_to @post do %><%= @post.title %><% end %></div>
      <div><%= link_to @post do %><img src="<%= @post.img %>" width="100%" height="100%"/><% end %></div>
      <%if !@post.taggings.empty?%>
        <div id="tags"><small>Tags: <%= raw tag_links(@post.all_tags) %></small></div>
      <%end %>
    </div>
  </div>

  <div class="welcome">
    <% if user_ownes_post?(@post) and user_signed_in? %>
      <%= link_to 'Edit', edit_post_path(@post) %>
      <%= link_to "Delete", post_path(@post),
                  :data => {:confirm => "Is this what you want?",
                            :method => "delete"}
      %>
      <br>
      <br>
    <% end %>
  </div>


<%= form_for [@post, Comment.new] do |f| %>
<%= f.text_area :body, :id=> "bodyComment", placeholder: "Add a comment..." %><br/>
<%= f.submit :id=> "submitIt"%>
<% end %>

  <div class="comment-section">
    <ul style="list-style-type:none">
      <%= render(partial: 'comments/comment', collection: @post.comments) %>
    </ul>
  </div>

</div>