config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: "tag"

  get 'profile/index'

  resources :posts do
  	resources :comments
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  resources :comments do
  	resources :comments
    put "like", to: "comments#upvote"
    put "dislike", to: "comments#downvote"
  end

  devise_for :users, controllers: { sessions: 'user/sessions' }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemeBrowser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <ul class="nav-menu" role="navigation">
      <li><%=link_to image_tag("meme-icon_small.png"), root_path%></li>
      <li class="site-name"><p>MemeBrowser</p></li>
      <li class="meme-search">
        <%= form_tag(posts_path, method: :get) do %>
          <%= text_field_tag :tag, params[:tag], autofocus: true, placeholder: "Search for memes", :id=>"searchField", :required => 'required' %>
          <%= submit_tag 'Submit', name: nil, :id=>"searchBtn" %>
        <% end %></li>
        <%=image_tag("new_post_small.png") %><li id="signin"><%= link_to 'New Post', new_post_path%></li>
      <% if user_signed_in? %>
        <%=image_tag("post-it.png") %><li id="signin"><%= link_to 'my posts', profile_index_path %> </li>
        <%=image_tag("reg3.png") %><li id="signup"><%= link_to 'sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <%=image_tag("login.png") %><li id="signin"><%= link_to 'login', new_user_session_path %></li>
        <%=image_tag("reg3.png") %><li id="signup"><%= link_to 'sign up', new_user_registration_path %> </li>
      <% end %>

    </ul>
  </header>
  <% if notice -%>
    <script>
      swal({
          title: "Success",
          text: '<%= notice %>',
          type: 'success',
          showConfirmButton: false,
          timer: 2000
      }).done();
    </script>
  <% end %>

  <% if alert -%>
    <p class="alert"><%= alert %></p>
  <% end %>


   <%= yield %>
  </body>


</html>